def method():
    print("how many distinct terms are in the sequence generated by "
          "a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?")

    n = 100

    results = set(a ** b for b in range(2, n+1) for a in range(2, n+1))
    print(f"{len(results)} distinct terms")
    return
