def method():
    print("how many distinct terms are in the sequence generated by "
          "a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?")

    n = 100

    results = set()
    for a in range(2, n+1):
        for b in range(2, n+1):
            results.add(a ** b)
    print(f"{len(results)} distinct terms")
    return
